# -*- coding: utf-8 -*-
"""OTP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Imum3fwRn5VGqgSuWWa-2BQ_ehoCf-9K
"""

import random

otp = random.randint(100000, 999999)
print(f"Your OTP is: {otp}")

stored_otp = otp

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_otp_via_email(user_email, otp):
    sender_email = "youremail@example.com"
    sender_password = "yourpassword"

    message = MIMEMultipart()
    message["From"] = sender_email
    message["To"] = user_email
    message["Subject"] = "Your OTP Code"

    body = f"Your OTP is: {otp}"
    message.attach(MIMEText(body, "plain"))

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, sender_password)
        text = message.as_string()
        server.sendmail(sender_email, user_email, text)
        server.quit()
        print("Email sent successfully")
    except Exception as e:
        print(f"Error: {e}")

# Example usage
user_email = input("Enter your email: ")
send_otp_via_email(user_email, stored_otp)

entered_otp = int(input("Enter the OTP you received: "))

if entered_otp == stored_otp:
    print("OTP verified successfully!")
else:
    print("Invalid OTP. Please try again.")